"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-86u+ann-lni!djybxc5dut!lrbb%4ud#yo#y=f+@#o0w(jx&oi',
)

DEBUG = False

_allowed_default = (
    'localhost,127.0.0.1,'
    'rocbeurope.org,www.rocbeurope.org,'
    'rocb-europe.org,www.rocb-europe.org,'
    'demo.rocbeurope.org,demo.rocb-europe.org,'
    'app.rocbeurope.org,rtc.rocbeurope.org'
)
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', _allowed_default).split(',')
    if h.strip()
]
CORS_ALLOWED_ORIGINS = [
    'https://rocbeurope.org',
    'https://www.rocbeurope.org',
    'https://demo.rocbeurope.org',
    'https://demo.rocb-europe.org',
    'https://rocb-europe.org',
    'https://www.rocb-europe.org',
]
# Application definition
CSRF_TRUSTED_ORIGINS = [
    'https://rocbeurope.org',
    'http://rocbeurope.org',
    'https://www.rocbeurope.org',
    'http://www.rocbeurope.org',
    'https://demo.rocbeurope.org',
    'http://demo.rocbeurope.org',
    'https://rocb-europe.org',
    'http://rocb-europe.org',
    'https://demo.rocb-europe.org',
    'http://demo.rocb-europe.org',
    'https://www.rocb-europe.org',
]

# Application definition
LOGIN_URL = '/login'

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'oneapp.apps.OneappConfig',

    # third party apps
    'ckeditor',
    'ckeditor_uploader',
    'rosetta',

    'about',
    "contact",
    "region",
    "account",
    "analytics",
    "publicity",
    "etraining",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'oneapp.middleware.languages.SetDefaultLangMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.i18n",
                'oneapp.context_processors.public_site_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

USE_POSTGRES = os.getenv('USE_POSTGRES', 'false').lower() == 'true'

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGES = [
    ('en', _('En')),
    ('ru', _('Ru')),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
PARLER_LANGUAGES = {
    None: (
        {'code': 'en', },
        {'code': 'ru', },
    ),
    'default': {
        'fallbacks': [],
        'hide_untranslated': False,
    }
}
LANGUAGE_CODE = 'en'
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
DEFAULT_LANGUAGE = 'en'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'Asia/Baku'
SITE_ID = 2

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
#
# static/          — source files in repo (STATICFILES_DIRS). Used by runserver when DEBUG=True.
# staticfiles/     — collectstatic output (STATIC_ROOT). Point nginx /static/ here when DEBUG=False.
# Do not set STATIC_ROOT to the same path as STATICFILES_DIRS.

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/'
CKEDITOR_UPLOAD_PATH = 'uploads'


SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'extraPlugins': 'blockquote',
        "versionCheck": False
    },
}
DATA_UPLOAD_MAX_MEMORY_SIZE = 12428800


TRANSLATABLE_MODEL_MODULES = ["oneapp.models", ]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Main site pulls global news from rocb_app_news API (root host for API is app.rocbeurope.org)
RTC_APP_NEWS_API_BASE = os.environ.get(
    'RTC_APP_NEWS_API_BASE',
    'https://app.rocbeurope.org/api/v1',
)

# Canonical origin for sitemaps, Open Graph, and robots.txt (no trailing slash).
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', 'https://rocbeurope.org').rstrip('/')

# Optional header X-Country-Owner-Api-Key for /api/region/country-owners/ (staff session also allowed)
COUNTRY_OWNER_BULK_API_KEY = os.environ.get('COUNTRY_OWNER_BULK_API_KEY', '')

# OpenAI page translation — set OPENAI_API_KEY in rocb_main/.env (see .env.example)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_TRANSLATE_MODEL = os.environ.get('OPENAI_TRANSLATE_MODEL', 'gpt-4o-mini')
OPENAI_TRANSLATE_MAX_HTML_LENGTH = int(os.environ.get('OPENAI_TRANSLATE_MAX_HTML_LENGTH', '48000'))
OPENAI_TRANSLATE_CHUNK_SIZE = int(os.environ.get('OPENAI_TRANSLATE_CHUNK_SIZE', '6000'))
OPENAI_TRANSLATE_TIMEOUT = int(os.environ.get('OPENAI_TRANSLATE_TIMEOUT', '90'))


# --- Outgoing email (Gmail SMTP) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "europerocb@gmail.com"
EMAIL_HOST_PASSWORD = "srvl cyqk tvzl odpc"
DEFAULT_FROM_EMAIL = "europerocb@gmail.com"

ROCB_NOTIFY_STAFF_EMAILS = [
    "info@rocb-europe.org",
    "nicat254memmedov@gmail.com",
]
